repo: "masthead-semantics"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 3
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    outline: true
    has:
      - "header"
      - "header img"
      - "header h1"
      - "header nav"
      - "header nav ul"
      - "header nav ul li"
      - "header nav ul li a"
      - "figure"
      - "figure img"
      - "figure figcaption"
      - "main"
      - "main p"
    search:
      - "The Solar System"
      - "Stars"
      - "Terrestrial planets"
      - "Gas giants"
      - "Dwarf planets"
      - "Asteroids"
      - "Comets"
      - "gravitationally"
